package:
  name: geopandas
  version: !!str 0.1.0.dev_bdfc7fb

source:
  git_url: https://github.com/geopandas/geopandas.git
  git_rev: bdfc7fb819a53246fb44ca91b260bb394f4177fb

requirements:
  build:
    - python
    - setuptools
    - pandas
    - shapely
    - fiona
    - descartes
    - pyproj

  run:
    - python
    - pandas
    - shapely
    - fiona
    - descartes
    - pyproj

test:
  imports:
    - geopandas
    - geopandas.io

about:
  home: http://geopandas.org
  license: BSD
  summary: 'Geographic pandas extensions'
