package:
  name: vis-framework
  version: "2.1.3"

source:
#  fn: vis-framework-2.1.3.tar.bz2
#  url: https://pypi.python.org/packages/source/v/vis-framework/vis-framework-2.1.3.tar.bz2
#  md5: e1529cf77ed3075a465895dd2596e80b
  git_url: https://github.com/maxalbert/vis-framework.git
  git_rev: 9c3758f2b087be605e8c6283caaf2a5c60de6d69

requirements:
  build:
    - python
    - setuptools
    - music21 >=2.0.3,<2.1
    - pandas >=0.14.1,<0.17

  run:
    - python
    - music21 >=2.0.3,<2.1
    - pandas >=0.14.1,<0.17
    - numexpr
    - bottleneck

test:
  imports:
    - outputlilypond
    - vis
    - vis.analyzers
    - vis.analyzers.experimenters
    - vis.analyzers.indexers
    - vis.models

  commands:
    - python $SRC_DIR/run_tests.py

  requires:
    - mock

about:
  home: http://elvisproject.ca/api/
  license: GNU Affero General Public License v3 or later (AGPLv3+)
  summary: 'The VIS Framework for Music Analysis'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
