package:
  name: vis-framework
  version: "2.3.1"

source:
#  fn: vis-framework-2.1.3.tar.bz2
#  url: https://pypi.python.org/packages/source/v/vis-framework/vis-framework-2.1.3.tar.bz2
#  md5: e1529cf77ed3075a465895dd2596e80b
  git_url: https://github.com/maxalbert/vis-framework.git
  #git_rev: eaa24a2506c14c21e5dd201493eec85335c9daed
  #git_rev: 358170d06015395fd5695ae36239c7d8f40bf53b
  git_rev: 990c9264b84271feb8375f07b635cef79e03d3b3

requirements:
  build:
    - python
    - setuptools
    - pandas >=0.14.1,<0.17
    - music21 >=2.2.1

  run:
    - python
    - setuptools
    - pandas >=0.14.1,<0.17
    - music21 >=2.2.1
    - numexpr
    - scipy
    - bottleneck

test:
  imports:
    - outputlilypond
    - vis
    - vis.analyzers
    - vis.analyzers.experimenters
    - vis.analyzers.indexers
    - vis.models

  commands:
    - python $SRC_DIR/run_tests.py

  #requires:
  #  - mock
  #  - scipy

about:
  home: http://elvisproject.ca/api/
  license: GNU Affero General Public License v3 or later (AGPLv3+)
  summary: 'The VIS Framework for Music Analysis'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
