package:
  name: memory_profiler
  version: "0.40"

source:
  fn: memory_profiler-0.40.tar.gz
  url: https://pypi.python.org/packages/source/m/memory_profiler/memory_profiler-0.40.tar.gz
  md5: 593d3adff124193e4205a36db9c5e82d

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - psutil

test:
  imports:
    - memory_profiler

about:
  home: http://pypi.python.org/pypi/memory_profiler
  license: BSD
  summary: module for monitoring memory usage of a python program
