package:
  name: oommf
  version: "12a6_20150930"

source:
  fn: oommf12a6_20150930.tar.gz
  url: http://math.nist.gov/oommf/dist/oommf12a6_20150930.tar.gz

build:
  number: 0

requirements:
  build:
    - tk ==8.5.18+maxalbert.0
  run:
    - tk ==8.5.18+maxalbert.0

test:
  commands:
    - oommf +version

about:
  home: http://math.nist.gov/oommf/
  license_file: LICENSE

# vim:set ts=8 sw=2 sts=2 tw=78 et:
