package:
  name: oommf
  version: "12a5bis_20120928"

source:
  fn: oommf12a5bis_20120928.tar.gz
  url: http://math.nist.gov/oommf/dist/oommf12a5bis_20120928.tar.gz

build:
  number: 0

requirements:
  build:
    - tk >=8.5,<8.6
  run:
    - tk >=8.5,<8.6

test:
  commands:
    - oommf +version

about:
  home: http://math.nist.gov/oommf/
  license_file: LICENSE

# vim:set ts=8 sw=2 sts=2 tw=78 et:
