package:
  name: music21
  version: "2.0.5"

source:
  fn: music21-2.0.5.tar.gz
  url: https://pypi.python.org/packages/source/m/music21/music21-2.0.5.tar.gz
  md5: 8f1c18fede0b9e5c74f7c142160839cd

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - music21

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/cuthbertLab/music21
  license: GNU Lesser General Public License v3 or later (LGPLv3+)
  summary: 'A Toolkit for Computer-Aided Musical Analysis and Manipulation.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
